---
- name: show ver
  hosts: all
  connection: local
  gather_facts: true

  vars:
  cli:
  username: admin
  password : cisco
  timeout : 100

  tasks:
  - name: cisco_sh_ver
  ios_command:
   commands:"show version"
  register: output
  provider : "{cli}"
