---
- name: show ver
  hosts: CISCO1
  connection: local
  gather_facts: false
  
  vars:
   cli:
    username: admin
    password: cisco
    ip_address: "{{ ansible_host }}"
  
  tasks:
    - name: run show version on remote devices
      register: version
      ios_command:
          commands: show version
      provider: “{{ cli }}”

    
