---
- name: cisco_sh_ver
  hosts: all
  connection: local

  vars:
    cli:
    username: "admin"
    password : "cisco"
    timeout : 100

  tasks:
   - name: SHOW VERSION
     ios_command:
         commands:"show version"
     register: output
     provider : "{cli}"
