---
- name: show ver
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: run show version on remote devices
      register: version
      ios_command:
          commands: show version

    
