---
- name: cisco_sh_ver_run
  hosts: all
  connection: local 
  
  tasks:
    - name: run show version on remote devices
      ios_command:
         commands: 
           -show version
           - show run
      register: output
    - debug: var=output.stdout_lines
