---
- name: cisco_sh_ver
  hosts: all
  gather_facts: true

  vars:
     cli:
     username: admin
     password : cisco
     timeout : 100

  tasks:
   - name: run show version
     cisco.ios.ios_command:
       commands:
         - show version
     provider : "{cli}"
     register: output
